spring:
  profiles:
    active: postgresql  # Default profile - change to 'mysql' to use MySQL

# Common properties that apply to all profiles
server:
  port: 9090

file:
  upload-dir: ./uploads

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWT1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789}
  access-token-expiration: 3000000
  refresh-token-expiration: 604800000

logging:
  level:
    org:
      springframework:
        boot:
          devtools: DEBUG
    com:
      yourpackage: DEBUG