spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_blog
    username: omrharbi
    password: omrharbi
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: DEALLOCATE ALL
      maximum-pool-size: 15   # lower this if too many connections open
      minimum-idle: 2
      idle-timeout: 1800000
      max-lifetime: 200
      connection-timeout: 1800000
  devtools:
    livereload:
      enabled: false
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update  #create-drop
    # show-sql: true
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.PostgreSQLDialect
 
file:
  upload-dir: ./uploads

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWT1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789}
  access-token-expiration: 3000000    # 15 minutes in milliseconds
  refresh-token-expiration: 604800000 # 7 days in milliseconds
server:
  port: 9090
 
logging:
  level:
    org:
      springframework:
        boot:
          devtools: DEBUG
    com:
      yourpackage: DEBUG