version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: springboot-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: omrharbi
      POSTGRES_PASSWORD: omrharbi
      POSTGRES_DB: db_blog
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
